In [ ]:
# References:
# https://stackoverflow.com/questions/17912307/u-ufeff-in-python-string
# https://stackoverflow.com/questions/3518778/how-do-i-read-csv-data-into-a-record-array-in-numpy
# https://stackoverflow.com/questions/60508233/python-implement-a-pca-using-svd
# https://medium.com/swlh/principal-component-analysis-from-scratch-in-python-2f139c6420c9#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg2MTY0OWU0NTAzMTUzODNmNmI5ZDUxMGI3Y2Q0ZTkyMjZjM2NkODgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2NTEyMDA1NjksImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExNzY0MzY3OTU5NDAyOTgwOTczNCIsImVtYWlsIjoidW5pdmVyc2VtaWxreXdheWdhbGF4eUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiMjE2Mjk2MDM1ODM0LWsxazZxZTA2MHMydHAyYTJqYW00bGpkY21zMDBzdHRnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwibmFtZSI6ImFteSBnIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBVFhBSnlvblMwV0lsNGxUNTBFMWh2dXZQRFZjdHZSYlJRcFJoWXBHV3FvPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6ImFteSIsImZhbWlseV9uYW1lIjoiZyIsImlhdCI6MTY1MTIwMDg2OSwiZXhwIjoxNjUxMjA0NDY5LCJqdGkiOiIxZTczZTZkZGNkMTY0ZDNmNmEwZTE5YjIzNmY2NjUyMGZhMzAxYzExIn0.fRIGRxlXOOQOEX0rRA0CP0aDQyz5Uls8yPwxyhvNLU7wqyafkCUVCEk_TEaV4yHprz-8IZQakYsoGdApNLpOMLsOJviO91ZGn0Fq7-Ig_IcL2Xe84RAw8qrIZOb5jMHMYS0-6uLe9-BIDntPNKE6IPWlxB4MSJhYyBccpoc4kx_LtcRzXodIJhpVxYQv1Rs1wJhztMYBhQwxNiyGzyWFoVS6e3jytjjG1g4J4mcVb3P9XVPzmN6i4XSa1g8D00K1zTbujFH1lC6GG6KMX7Xas-MpzBcyA3UjRYAjuE0Aps1zGGpwzGjMSWMRy3t-ChEo5piFSOQ69L4yPqWWs-VoDg

In [1]:
import numpy as np
import csv
import pandas as pd

######### data reading #############

train_x_data = pd.read_csv('train_images.csv', header=None)
train_x_data = train_x_data.to_numpy()
print('train_x_data',train_x_data)

train_x_data [[ 95 101  99 ... 116 118  96]
 [ 91  92  91 ... 100  90  81]
 [ 87  70  72 ...  80  84  90]
 ...
 [133 102 121 ... 130 131 111]
 [118 117 115 ... 100 100 109]
 [ 74  89  92 ... 126 116 106]]


In [2]:
mean_of_features = np.mean(train_x_data,axis = 0) #mean from each column/feature
#calculate variance matrix 
diff_from_mean = train_x_data - mean_of_features # get (x-mean)
# print(diff_from_mean)
covariance_matrix = np.cov(diff_from_mean.T) # get covariance x-mean*x-mean
# print(covariance_matrix)
eigen_values,eigen_vectors = np.linalg.eig(covariance_matrix) #get eigen values and vectors
#sorting eigen values in descending order
sorted_indices_eigen_values = np.argsort(eigen_values) #get indices in descending order of eigen values
sorted_eigen_values = eigen_values[sorted_indices_eigen_values[::-1]] #extract the eigen values
sorted_eigen_vectors = eigen_vectors[sorted_indices_eigen_values[::-1]] #extract the eigen vectors
print(sorted_eigen_values)

[ 5.47229952e+06+0.00000000e+00j  2.48519498e+05+0.00000000e+00j
  9.13498065e+04+0.00000000e+00j ... -5.43398258e-11+2.40537157e-11j
 -5.43398258e-11-2.40537157e-11j -1.16090293e-10+0.00000000e+00j]


In [22]:
sorted_eigen_vectors1 = sorted_eigen_vectors [:,:1] #get first 1 component #you can change component here
print('sorted_eigen_vectors1:',sorted_eigen_vectors1.shape)
print('diff_from_mean:',diff_from_mean.shape)

sorted_eigen_vectors1: (12100, 1)
diff_from_mean: (7000, 12100)


In [23]:
new_train_x_data = np.dot(sorted_eigen_vectors1.T,diff_from_mean.T).T #take dot product of eigen vector and diff_from_mean vector
print(new_train_x_data.shape)

(7000, 1)


In [24]:
new_train_x_data_real = np.real(new_train_x_data) #getting only the real numbers and discarding imaginary numbers

In [25]:
#writing the newly reduced dimension data to file
df = pd.DataFrame(new_train_x_data_real)
df.to_csv('1_dim_train_data.csv',header=False,index=False)

In [17]:
############ test data #####################
test_x_data = pd.read_csv('test_images.csv', header=None)
test_x_data = test_x_data.to_numpy()
# print('test_x_data',train_x_data)


test_x_data 

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [26]:
diff_from_mean_test = test_x_data - mean_of_features # use the mean vector from PCA and subtract from test x
new_test_x_data = np.dot(sorted_eigen_vectors1.T,diff_from_mean_test.T).T ##take dot product of eigen vector and diff_from_mean vector
new_test_x_data_real = np.real(new_test_x_data) #getting only the real numbers and discarding imaginary numbers

In [27]:
df2 = pd.DataFrame(new_test_x_data_real)
df2.to_csv('1_dim_test_data.csv',header=False,index=False)

In [20]:
np.set_printoptions(threshold=np.inf,suppress=True)


#calculating variance
variance = sorted_eigen_values/sorted_eigen_values.sum()
variance = np.real(variance)
print(variance)
# output:
# [ 6.86386363e-01+1.52999674e-33j  3.11716114e-02+6.94834080e-35j
#   1.14579367e-02+2.55404342e-35j ... -6.81580299e-18+3.01703925e-18j
#  -6.81580299e-18-3.01703925e-18j -1.45611170e-17-3.24576109e-50j]

[ 0.68638636  0.03117161  0.01145794  0.00876351  0.00420586  0.00411727
  0.00308045  0.0024957   0.00220746  0.00199519  0.00181278  0.00168051
  0.00154883  0.00149962  0.00136606  0.00131942  0.00125629  0.00119712
  0.00114293  0.001116    0.00107783  0.00104786  0.00100046  0.00091984
  0.00089971  0.00085555  0.00084544  0.00083469  0.00081395  0.00079477
  0.00077876  0.00074183  0.00073035  0.00071142  0.00068318  0.00068063
  0.00065416  0.00064931  0.00063076  0.0006196   0.0005976   0.00058331
  0.0005752   0.00056664  0.00055168  0.0005378   0.00053209  0.00052231
  0.00051259  0.00050506  0.00049831  0.00049608  0.00048746  0.00047941
  0.00047503  0.00046585  0.00045796  0.00045506  0.0004465   0.00043958
  0.0004357   0.00043386  0.00042885  0.00042466  0.00041726  0.00041089
  0.00040499  0.00040172  0.00039649  0.00039176  0.00038958  0.00038752
  0.00038386  0.00037971  0.00037779  0.00037354  0.00037059  0.00036855
  0.00036732  0.00036265  0.00035727  0.00035324  0